### ISSUE TITLE
Build CLI for de/encryption and validation

### ISSUE THREAD

**Issue by mohoff** [strong-config/node#11]
Currently, configs are used in a way that `strongConfig.load()` is called which returns a decrypted config object.

For a broader range of use-cases, incl. CI, we want to provide a CLI interface that allows encryption and decryption of files.

Commands to consider:
- `strong-config decrypt [--all] [<path-to-file>] [<environment>]`
- `strong-config encrypt [--all] [<path-to-file>] [<environment>]`
- `strong-config validate [--all] [<path-to-file>] [<environment>]`

In these commands, exactly one of the arguments must be present to form a valid command.

More thoughts:
- Different output formats could be useful as well: `--output/-o yaml/json/` OR `--in-place`.
- Extraneous arguments should be forwarded to the `sops` binary

**Comment by chapati23** [comment]
just a process comment. this issue doesn't really involve this repo. for these more general high-level ideas/tickets, i'd suggest to use the org-level project board. there is in fact already a card for this: https://github.com/orgs/strong-config/projects/1#card-24634933

the cards aren't as powerful as issues in terms of commenting. so we could also just go ahead and create a https://github.com/strong-config/cli repo and start discussing there in a new issue what this should look like.

**Comment by mohoff** [comment]
I thought of it more as a `strong-config/node` thing. But fair point, in the light of a `/cli` project, we can move this

**Comment by chapati23** [comment]
I've created https://github.com/strong-config/cli/issues/1 now as a temporary umbrella ticket for the CLI project. Let's close this and move discussions over there.
