### ISSUE TITLE
Remove custom eslint config and extend from `@brickblock/eslint-config-base-ts` instead

### ISSUE THREAD

**Issue by mohoff** [strong-config/node#12]
Currently, the eslint rule setup defines a bunch of custom rules to get a feeling for useful and annoying rules in Typescript projects.

Once we're happy with a ruleset, we should backport the configuration to `@brickblock/eslint-config-base-ts` and extend from it in this project.

- [x] More research on which (typescript-specifc?) rules we want
- [x] Update `@brickblock/eslint-config-base-ts`
- [x] Extend from `@brickblock/eslint-config-base-ts` here

**Comment by chapati23** [comment]
My suggestion for the initial ruleset is effectively `@brickblock/eslint-config-base-ts` which simply uses [`@typescript-eslint/recommended`](https://github.com/typescript-eslint/typescript-eslint/blob/67537b863a8a98383796abb404224fdfc1c7b996/packages/eslint-plugin/src/configs/recommended.json
).

Happy to discuss more specific rules when you have any in mind. I figured it's safest to start with the defaults until we have more experience with TS.

**Comment by chapati23** [comment]
fixed in [a24f08d](https://github.com/strong-config/node/commit/a24f08d648f10e7686078c09f561c676796b50f3)
