### ISSUE TITLE
Create CONTRIBUTING.md to help open source devs onboard

### ISSUE THREAD

**Issue by PaddyMc** [strong-config/node#15]
Create a CONTRIBUTING.md file, It will help attract open-source devs and also give people a good idea of our values.

[Reasoning](https://mozillascience.github.io/working-open-workshop/contributing/)
[Example](https://gist.github.com/PurpleBooth/b24679402957c63ec426)

**Comment by mohoff** [comment]
great! @PaddyMc wanna pick it up?

**Comment by PaddyMc** [comment]
Would love to @mohoff , but unfortunately, I don't have the availability to complete this task atm.
