### ISSUE TITLE
Add git hook scripts

### ISSUE THREAD

**Issue by mohoff** [strong-config/node#28]
The strongest selling point of `strong-config/node` is having secrets in your configs that you can commit-push like any other file. No need for using `.gitignore`, which can easily forgotten about.

However, users can still forget to encrypt their configs (assuming they contain secrets). To avoid this as best as possible, let's build helpers that can be used as pre-commit hook (and pre-push hook if desired by the user) to avoid committing/pushing secrets. These helpers can be run with `husky` and `lint-staged` for example.

This means we extend the existing `strong-config validate` or build a second command, e.g. `strong-config sanity`.

_Option 1:_
- Extend functionality of `strong-config validate`, so it validates the config files against the schema _and_ checks if all configs are encrypted.

_Option 2:_
- Add a new command `strong-config sanity` (or similar name) that makes sure that all configs are encrypted. Leave `strong-config validate` as is. Both commands can be used together in git hooks.

A class-based invocation could make sense as well: `new StrongConfig({..}).sanityCheck()`

We have to discuss if we implement that in `strong-config/node` or `strong-config/cli`, or both.

**Comment by chapati23** [comment]
This is done essentially. We have the `strong-config check [optional-path-to-specific-file]` command now which can be run on `pre-commit`.
