### ISSUE TITLE
Improve generated Typescript interfaces

### ISSUE THREAD

**Issue by mohoff** [strong-config/node#6]
Currently, the compiled types are written into a `strongconfig.d.ts`. It also exports an interface representing the top-level `Config` type.

1. Investigate,
    -  if there's a better util to generate types. 
    - if it makes more sense to generate `type`s instead of `interface`s
2. Improve type generation with:
    - Remove `[k: string]: any` of all generated interfaces
    - Implement check that `title` of a json-schema definition can not be named `Config` as it's reserved for the top-level interface we append
    - Improve header: Replace warning. Is `tslint:disable` needed?

**Comment by chapati23** [comment]
@mohoff after we've learned about `"additionalProperties": false`, is this ticket still required?

**Comment by mohoff** [comment]
The majority of todos in OP is resolved. The only thing left is 2.3 but i'd say that's so minor that I'm closing for now.
