### ISSUE TITLE
Documentation site is down

### ISSUE THREAD

**Issue by araphiel** [strong-config/node#74]
The domain for the documentation website does not appear to work

**Comment by chapati23** [comment]
Thanks for the heads up, seems like Notion has changed the way it can be integrated with custom domains via Cloudflare again..I’ll look into it when I find some time

**Comment by chapati23** [comment]
@araphiel i removed the url masking and strong-config.dev should be working again (it's just a naked redirect to a notion page now, notion is trying everything they can to make people pay for their custom domain service, it seems...)
