### ISSUE TITLE
Allow configuration of strong-config by passing a config obj into constructor

### ISSUE THREAD

**Issue by mohoff** [strong-config/node#8]
The constructor of StrongConfig should accept a configuration object with various fields that configure the behavior of strong-config.

Preliminary configuration fields:

```
runtimeEnvironmentVariable: string (DEFAULT: 'runtimeEnvironment')
generateTypes: boolean (DEFAULT: true)
generatedTypesPath: string (DEFAULT: 'strongconfig.d.ts')
generatedTypeRoot: string   (DEFAULT: 'Config')
substitutionPattern: string   (DEFAULT: /\${(\w+)}/g)
environments: string[] (DEFAULT: ['development', 'production'])
configDir: string (DEFAULT: 'config/')
schemaFile: string (DEFAULT: 'config/schema.json')
logger: Logger (DEFAULT: internal bunyan instance) --> interface matters here: debug/info/warn/error?
```

Things to take care of:

- [ ] Support passing a configuration object
- [ ] Validate the passed configuration object
- [ ] Replace existing hard-coded values in code with configuration obj values

**Comment by chapati23** [comment]
I like this idea :)

Some thoughts on the individual params

1. `runtimeEnvironmentVariable`
Usually I'm not a friend of shorthands and try to err on the side of clarity. However, I think `env` is so common in the field of software engineering that I'd consider it safe to just make this `runtimeEnv` instead.

1. `generatedTypesPath`
This feels a bit redundant to `configDir`. Is this only about the name of the types file or do we really wanna allow this file to live outside the `config` dir? If it's only about name, I'd say `generatedTypesFileName` is clearer. If we want to allow customising this path _in addition_ to `configDir` => what's a scenario where that's useful?

1. `generatedTypeRoot`
Had to read twice here to understand what you mean. My brain auto-corrected this to `generatedTypeName`. Wdyt?

1. `substitutionPattern`
What's this again?

1. `environments`
nit: I feel like this should be the top-listed config option. I think this is probably the thing that people would customise most often.

1. `schemaFile`
Similar to the above. What's a realistic scenario where we would _not_ want to have the schema file live inside the `configDir`?

1. `logger`
Not sure I understand your comment here. If it's about what `logLevel` to default to, then `error` is safest.

**Comment by mohoff** [comment]
1. Are you referring to the default value or the variable name?

2. I'm not sure yet myself. Depends where external types usually go to in Typescript projects. We're also having a special case where we not only type or module but generate types dynamically.

3. Is `generatedRootType` better?

4. A regexp that matches currently any `${VAR}` in the config and replaces it with `process.env[VAR]`. Could be customized to `<VAR>` or `$VAR` or etc.

5. jup

6. Forcing the user to have a `config/schema.json` is too opinionated imo. I don't see a reason to not make this configurable. Let the users decide where they want to put their schema file.

7. The idea is to let the user pass a custom logger instance into `StrongConfig`. If such a logger is not provided, we would construct our own internal bunyan logger as fallback. To cover both cases, the logger needs a well-defined interface, since in our code we'll just call  `logger.error/info/etc`. This assumes the passed logger instance must expose `error()/info()/etc.`

**Comment by chapati23** [comment]
1. both :)
1. let's keep it simple to start then. IMO defaulting to `<configDir>/strong-config.d.ts` should be a very sane default and for an MVP, i'd even be ok with not making this path configurable at all if we're not sure we need it yet.
1. I think the reason I preferred `Name` instead of `Root` was that `Root` to me suggests that there's many many sub-types that somehow inherit or extend from the root, when in fact it's really just _one_ type we're generating.
1. thx 👍
1. ✅
1. Ok, here I'm less opinionated. Just wanted to save us some time. Happy either way.
1. I see. We shouldn't reinvent the wheel here thene. We can't also be the first ones running into this issue. Can u do a bit of research how other popular libraries handle this issue?

**Comment by mohoff** [comment]
3. That's what happens actually. The library we're using generates an interface hierarchy with one 'root' interface, which connects all subtypes either directly or indirectly.

7. Reinvent wheel where? I mean we're accepting an optional logger, and in case none is passed we're constructing our own one. Will do research 👍 

All good with the other points:)

**Comment by chapati23** [comment]
3. Wut, ok that’s different than how it worked with flow then. What’s the advantage of these various interfaces inheriting from each other vs just one simple type that describes the whole object?

4. I meant that it must be a common pattern for an npm package to accept an external logger so my guess is that there may be some best practices on what functions a logger abstraction typically implements

**Comment by mohoff** [comment]
3. Dunno, but the module we're using, `json-schema-to-typescript`, does this by default and there's no option to turn it off. But didn't seem like a dealbreaker to me.

4. Ok. Couldn't find good examples so far.

**Comment by chapati23** [comment]
3. just played with their [example repo](https://github.com/bcherny/json-schema-to-typescript/tree/master/example) a little bit and maybe this discussion is void anyways. As far as I can see `json-schema-to-typescript` just takes what's in the `title` key of the schema and uses that as the name for the root type. So it _is_ already configurable via the schema and we shouldn't need to expose this option in addition.

**Comment by chapati23** [comment]
Another issue I see here is that this could make using strong-config across several different files a bit more complicated.

Currently we just do this in every file that needs access to the config object:

```js
const config = require('@brickblock/strong-config').load()
```

If we have some options now you'd either have to do:

```js
const config = require('@brickblock/strong-config').load({ repeat: 'all', options: 'everwhere'})
```

or include them from some common place

```js
const options require('../../../../config-options')
const config = require('@brickblock/strong-config').load(options)
```

Any way to get around having to re-define the options in every place we're loading the config?

**Comment by mohoff** [comment]
Yes: https://github.com/strong-config/node/issues/7#issuecomment-537974800

Regarding 3.: Exactly, that's what i'm already making use of in https://github.com/strong-config/node/pull/5. Pls read https://github.com/strong-config/node/blob/f17289318cd43104c0d3a2e5d533c46ad631dd5d/src/utils/generate-type-from-schema.ts#L30 for what `generatedTypeRoot` potentially configures. The file will give you a good overview on how `json-schema-to-typescript` is used already.

The fact that the library just takes the title of the top-level schema definition seemed hacky and inflexible to me. That's why I'm extending from that to always have a type named `Config`.

**Comment by chapati23** [comment]
Interesting, to me it doesn't feel hacky at all. Because the user already has the option to configure the schema title. And it also makes sense to me that there's a mapping of schema title to type name.

Feels like a super edge case that somebody would want to use different names for their schema than the root type, I think we should start simple here. If it becomes a requirement we can always add it later.

**Comment by mohoff** [comment]
Hmm. A user might want to set the top-level title to `The config we use for our microservice X` which would generate him

```js
// strong-config.d.ts
...
interface TheConfigWeUseForOurMicroserviceX {
  ...
}
```

Don't think that's convenient. That's why we should always extend from that:

```js
interface Config extends TheConfigWeUseForOurMicroserviceX {
  runtimeEnvironment: string,
}
```

Now, users can always use `Config` as static type name. That'd be the default. In case a different name is desired, he can pass the option `generatedRootType: AppConfig` (e.g.) to overwrite the default.

**Comment by chapati23** [comment]
aight, if it doesn't add too much extra code to maintain, i'm ok with it.

**Comment by mohoff** [comment]
The _extending from the root type_ is already in master. You be the judge :)

The config params are clear then 👍

**Comment by mohoff** [comment]
#27 implements requirements from OP but please note:

- `generateTypes` was removed. This is integrated by setting `types: false`.
- `logger` isn't done yet. Let's bring this up again when we have logging internally.
- `environments` is not implemented. This is because it doesn't come from the params but is dynamically resolved through the value of `runtimeEnv`.
- slightly renamed some params.
